from typing import Callable


class Signal:
    def __init__(self) -> None: ...
    def slot_count() -> int: ...
    def connect(cb: Callable) -> int: ...
    def disconnect(handle: int): ...
    def disconnect_all(): ...
    def emit(*args): ...
    def __call__(self, *args): ...
