from typing import Callable


class Signal:
    def __init__(self) -> None: ...
    def slot_count(self) -> int: ...
    def connect(self, cb: Callable) -> int: ...
    def disconnect(self, handle: int): ...
    def disconnect_all(self): ...
    def emit(self, *args): ...
    def __call__(self, *args): ...
