add_rules("mode.debug", "mode.release")

add_requires("utf8.h")

target("rolui")
set_languages("cxx17")
set_kind("static")
add_files("src/*.cpp")
add_headerfiles("include/(RolUI/*.hpp)")
add_includedirs("include/", { public = true })
target_end()

target("rolui-events")
set_languages("cxx17")
set_kind("static")
add_files("RolUI-events/*.cpp")
add_headerfiles("include/(RolUI-events/*.hpp)")
add_deps("rolui")
add_packages("utf8.h", { public = true })
target_end()

target("rolui-widgets")
set_languages("cxx17")
set_kind("static")
add_files("RolUI-widgets/*.cpp")
add_headerfiles("include/(RolUI-widgets/*.hpp)")
add_deps("rolui", "rolui-events")
add_packages("utf8.h", { public = true })
target_end()

includes("backend")
includes("examples")
