from typing import Tuple, Callable
from PyRolUI import Point, Size, IPainter, Window


class GLFWppWindow:
    def __init__(self, x: int, y: int, title: str): ...
    def make_opengl_context(self) -> bool: ...
    def poll_events(self): ...
    def wait_events(self): ...
    def wait_events_timeout(self,timeout: float): ...
    def set_title(self,title: str): ...
    def set_size(self,x: int, y: int): ...
    def window_pos(self) -> Tuple[int, int]: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def window_size(self) -> Tuple[int, int]: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def cursor_pos(self) -> Tuple[float, float]: ...
    def should_close(self) -> bool: ...
    def hide(self): ...
    def show(self): ...
    def swap_buffer(self): ...
    def close(self): ...
    on_exit: Callable
    on_size: Callable[[int, int], None]
    on_char: Callable[[int], None]
    on_cursor_enter: Callable
    on_cursor_leave: Callable
    on_cursor_pos: Callable[[float, float], None]
    on_mouse_button: Callable[[int, int, int], None]
    on_scroll: Callable[[float, float], None]


class GLFWWindow(GLFWppWindow, Window):
    def __init__(self, x: int, y: int, title: str): ...
    def pos(self) -> Point: ...
    def size(self) -> Size: ...
    def painter(self) -> IPainter: ...
    def begin_draw(self): ...
    def end_draw(self): ...
    def dispatch_event(self,timeout: float): ...

